services:
  nginx-proxy:
    build: ./nginx
    container_name: nginx-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - config-manager

  config-manager:
    build: ./config-manager
    container_name: config-manager
    volumes:
      - ./nginx/conf.d:/output
      - ../alumnos.csv:/config/alumnos.csv:ro
    environment:
      - DOMAIN=servidorgp.somosdelprieto.com
    command: ["python", "generate.py"]
    restart: "no"
